--Q12 MONTO PENDIENTE POR COBRAR

SELECT SUM(CRO.nMontoFinal)
FROM DB_INMOBISOFT_2.contratos.Cronograma CRO
WHERE CRO.dFechaPago IS NULL


--Q13 MONTO VENCIDO AUN NO PAGADO

SELECT SUM(CRO.nMontoFinal)
FROM DB_INMOBISOFT_2.contratos.Cronograma CRO
WHERE CRO.dFechaPago IS NULL
AND CRO.dFechaVencimiento<GETDATE()

--Q14 CUOTAS VENCIDAS Y SIN PAGAR

SELECT COUNT(CRO.nIdCronograma) AS CANTIDAD_CUOTAS
FROM DB_INMOBISOFT_2.contratos.Cronograma CRO
WHERE CRO.dFechaPago IS NULL
AND CRO.dFechaVencimiento<GETDATE()

--Q15 PORCENTAJE DE COBRANZA

SELECT (SUM(CASE WHEN CRO.dFechaPago IS NOT NULL THEN CRO.nMontoFinal END)/NULLIF(SUM(CRO.nMontoFinal),0)*100) AS PORCENTAJE
FROM DB_INMOBISOFT_2.contratos.Cronograma CRO
